<?php
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('AFG', '%s')", "Afghanistan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ALA', '%s')", "Åland Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ALB', '%s')", "Albania" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('DZA', '%s')", "Algeria" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ASM', '%s')", "American Samoa" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('AND', '%s')", "Andorra" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('AGO', '%s')", "Angola" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('AIA', '%s')", "Anguilla" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ATG', '%s')", "Antigua and Barbuda" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ARG', '%s')", "Argentina" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ARM', '%s')", "Armenia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ABW', '%s')", "Aruba" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('AUS', '%s')", "Australia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('AUT', '%s')", "Austria" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('AZE', '%s')", "Azerbaijan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BHS', '%s')", "Bahamas" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BHR', '%s')", "Bahrain" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BGD', '%s')", "Bangladesh" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BRB', '%s')", "Barbados" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BLR', '%s')", "Belarus" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BEL', '%s')", "Belgium" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BLZ', '%s')", "Belize" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BEN', '%s')", "Benin" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BMU', '%s')", "Bermuda" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BTN', '%s')", "Bhutan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BOL', '%s')", "Bolivia (Plurinational State of)" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BES', '%s')", "Bonaire, Sint Eustatius and Saba" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BIH', '%s')", "Bosnia and Herzegovina" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BWA', '%s')", "Botswana" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BRA', '%s')", "Brazil" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('VGB', '%s')", "British Virgin Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BRN', '%s')", "Brunei Darussalam" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BGR', '%s')", "Bulgaria" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BFA', '%s')", "Burkina Faso" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BDI', '%s')", "Burundi" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CPV', '%s')", "Cabo Verde" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('KHM', '%s')", "Cambodia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CMR', '%s')", "Cameroon" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CAN', '%s')", "Canada" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CYM', '%s')", "Cayman Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CAF', '%s')", "Central African Republic" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TCD', '%s')", "Chad" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CHL', '%s')", "Chile" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CHN', '%s')", "China" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('HKG', '%s')", "China, Hong Kong Special Administrative Region" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MAC', '%s')", "China, Macao Special Administrative Region" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('COL', '%s')", "Colombia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('COM', '%s')", "Comoros" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('COG', '%s')", "Congo" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('COK', '%s')", "Cook Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CRI', '%s')", "Costa Rica" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CIV', '%s')", "Côte d'Ivoire" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('HRV', '%s')", "Croatia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CUB', '%s')", "Cuba" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CUW', '%s')", "Curaçao" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CYP', '%s')", "Cyprus" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CZE', '%s')", "Czech Republic" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PRK', '%s')", "Democratic People's Republic of Korea" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('COD', '%s')", "Democratic Republic of the Congo" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('DNK', '%s')", "Denmark" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('DJI', '%s')", "Djibouti" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('DMA', '%s')", "Dominica" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('DOM', '%s')", "Dominican Republic" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ECU', '%s')", "Ecuador" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('EGY', '%s')", "Egypt" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SLV', '%s')", "El Salvador" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GNQ', '%s')", "Equatorial Guinea" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ERI', '%s')", "Eritrea" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('EST', '%s')", "Estonia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ETH', '%s')", "Ethiopia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('FRO', '%s')", "Faeroe Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('FLK', '%s')", "Falkland Islands (Malvinas)" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('FJI', '%s')", "Fiji" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('FIN', '%s')", "Finland" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('FRA', '%s')", "France" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GUF', '%s')", "French Guiana" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PYF', '%s')", "French Polynesia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GAB', '%s')", "Gabon" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GMB', '%s')", "Gambia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GEO', '%s')", "Georgia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('DEU', '%s')", "Germany" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GHA', '%s')", "Ghana" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GIB', '%s')", "Gibraltar" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GRC', '%s')", "Greece" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GRL', '%s')", "Greenland" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GRD', '%s')", "Grenada" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GLP', '%s')", "Guadeloupe" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GUM', '%s')", "Guam" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GTM', '%s')", "Guatemala" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GGY', '%s')", "Guernsey" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GIN', '%s')", "Guinea" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GNB', '%s')", "Guinea-Bissau" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GUY', '%s')", "Guyana" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('HTI', '%s')", "Haiti" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('VAT', '%s')", "Holy See" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('HND', '%s')", "Honduras" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('HUN', '%s')", "Hungary" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ISL', '%s')", "Iceland" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('IND', '%s')", "India" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('IDN', '%s')", "Indonesia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('IRN', '%s')", "Iran (Islamic Republic of)" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('IRQ', '%s')", "Iraq" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('IRL', '%s')", "Ireland" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('IMN', '%s')", "Isle of Man" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ISR', '%s')", "Israel" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ITA', '%s')", "Italy" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('JAM', '%s')", "Jamaica" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('JPN', '%s')", "Japan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('JEY', '%s')", "Jersey" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('JOR', '%s')", "Jordan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('KAZ', '%s')", "Kazakhstan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('KEN', '%s')", "Kenya" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('KIR', '%s')", "Kiribati" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('KWT', '%s')", "Kuwait" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('KGZ', '%s')", "Kyrgyzstan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LAO', '%s')", "Lao People's Democratic Republic" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LVA', '%s')", "Latvia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LBN', '%s')", "Lebanon" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LSO', '%s')", "Lesotho" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LBR', '%s')", "Liberia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LBY', '%s')", "Libya" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LIE', '%s')", "Liechtenstein" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LTU', '%s')", "Lithuania" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LUX', '%s')", "Luxembourg" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MDG', '%s')", "Madagascar" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MWI', '%s')", "Malawi" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MYS', '%s')", "Malaysia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MDV', '%s')", "Maldives" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MLI', '%s')", "Mali" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MLT', '%s')", "Malta" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MHL', '%s')", "Marshall Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MTQ', '%s')", "Martinique" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MRT', '%s')", "Mauritania" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MUS', '%s')", "Mauritius" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MYT', '%s')", "Mayotte" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MEX', '%s')", "Mexico" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('FSM', '%s')", "Micronesia (Federated States of)" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MCO', '%s')", "Monaco" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MNG', '%s')", "Mongolia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MNE', '%s')", "Montenegro" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MSR', '%s')", "Montserrat" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MAR', '%s')", "Morocco" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MOZ', '%s')", "Mozambique" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MMR', '%s')", "Myanmar" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NAM', '%s')", "Namibia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NRU', '%s')", "Nauru" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NPL', '%s')", "Nepal" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NLD', '%s')", "Netherlands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NCL', '%s')", "New Caledonia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NZL', '%s')", "New Zealand" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NIC', '%s')", "Nicaragua" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NER', '%s')", "Niger" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NGA', '%s')", "Nigeria" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NIU', '%s')", "Niue" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NFK', '%s')", "Norfolk Island" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MNP', '%s')", "Northern Mariana Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('NOR', '%s')", "Norway" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('OMN', '%s')", "Oman" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PAK', '%s')", "Pakistan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PLW', '%s')", "Palau" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PAN', '%s')", "Panama" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PNG', '%s')", "Papua New Guinea" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PRY', '%s')", "Paraguay" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PER', '%s')", "Peru" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PHL', '%s')", "Philippines" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PCN', '%s')", "Pitcairn" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('POL', '%s')", "Poland" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PRT', '%s')", "Portugal" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PRI', '%s')", "Puerto Rico" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('QAT', '%s')", "Qatar" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('KOR', '%s')", "Republic of Korea" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MDA', '%s')", "Republic of Moldova" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('REU', '%s')", "Réunion" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ROU', '%s')", "Romania" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('RUS', '%s')", "Russian Federation" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('RWA', '%s')", "Rwanda" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('BLM', '%s')", "Saint Barthélemy" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SHN', '%s')", "Saint Helena" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('KNA', '%s')", "Saint Kitts and Nevis" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LCA', '%s')", "Saint Lucia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MAF', '%s')", "Saint Martin (French part)" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SPM', '%s')", "Saint Pierre and Miquelon" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('VCT', '%s')", "Saint Vincent and the Grenadines" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('WSM', '%s')", "Samoa" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SMR', '%s')", "San Marino" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('STP', '%s')", "Sao Tome and Principe" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SAU', '%s')", "Saudi Arabia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SEN', '%s')", "Senegal" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SRB', '%s')", "Serbia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SYC', '%s')", "Seychelles" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SLE', '%s')", "Sierra Leone" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SGP', '%s')", "Singapore" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SXM', '%s')", "Sint Maarten (Dutch part)" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SVK', '%s')", "Slovakia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SVN', '%s')", "Slovenia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SLB', '%s')", "Solomon Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SOM', '%s')", "Somalia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ZAF', '%s')", "South Africa" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SSD', '%s')", "South Sudan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ESP', '%s')", "Spain" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('LKA', '%s')", "Sri Lanka" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('PSE', '%s')", "State of Palestine" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SDN', '%s')", "Sudan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SUR', '%s')", "Suriname" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SJM', '%s')", "Svalbard and Jan Mayen Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SWZ', '%s')", "Swaziland" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SWE', '%s')", "Sweden" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('CHE', '%s')", "Switzerland" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('SYR', '%s')", "Syrian Arab Republic" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TJK', '%s')", "Tajikistan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('THA', '%s')", "Thailand" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('MKD', '%s')", "The former Yugoslav Republic of Macedonia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TLS', '%s')", "Timor-Leste" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TGO', '%s')", "Togo" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TKL', '%s')", "Tokelau" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TON', '%s')", "Tonga" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TTO', '%s')", "Trinidad and Tobago" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TUN', '%s')", "Tunisia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TUR', '%s')", "Turkey" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TKM', '%s')", "Turkmenistan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TCA', '%s')", "Turks and Caicos Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TUV', '%s')", "Tuvalu" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('UGA', '%s')", "Uganda" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('UKR', '%s')", "Ukraine" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ARE', '%s')", "United Arab Emirates" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('GBR', '%s')", "United Kingdom of Great Britain and Northern Ireland" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('TZA', '%s')", "United Republic of Tanzania" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('USA', '%s')", "United States of America" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('VIR', '%s')", "United States Virgin Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('URY', '%s')", "Uruguay" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('UZB', '%s')", "Uzbekistan" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('VUT', '%s')", "Vanuatu" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('VEN', '%s')", "Venezuela (Bolivarian Republic of)" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('VNM', '%s')", "Viet Nam" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('WLF', '%s')", "Wallis and Futuna Islands" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ESH', '%s')", "Western Sahara" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('YEM', '%s')", "Yemen" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ZMB', '%s')", "Zambia" ));
$wpdb->query( $wpdb->prepare("INSERT INTO {$wpdb->projectmanager_countries} (code, name) VALUES ('ZWE', '%s')", "Zimbabwe" ));
?>