INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("AFG", "Afghanistan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ALA", "Åland Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ALB", "Albania");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("DZA", "Algeria");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ASM", "American Samoa");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("AND", "Andorra");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("AGO", "Angola");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("AIA", "Anguilla");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ATG", "Antigua and Barbuda");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ARG", "Argentina");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ARM", "Armenia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ABW", "Aruba");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("AUS", "Australia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("AUT", "Austria");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("AZE", "Azerbaijan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BHS", "Bahamas");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BHR", "Bahrain");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BGD", "Bangladesh");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BRB", "Barbados");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BLR", "Belarus");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BEL", "Belgium");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BLZ", "Belize");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BEN", "Benin");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BMU", "Bermuda");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BTN", "Bhutan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BOL", "Bolivia (Plurinational State of)");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BES", "Bonaire, Sint Eustatius and Saba");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BIH", "Bosnia and Herzegovina");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BWA", "Botswana");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BRA", "Brazil");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("VGB", "British Virgin Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BRN", "Brunei Darussalam");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BGR", "Bulgaria");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BFA", "Burkina Faso");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BDI", "Burundi");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CPV", "Cabo Verde");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("KHM", "Cambodia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CMR", "Cameroon");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CAN", "Canada");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CYM", "Cayman Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CAF", "Central African Republic");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TCD", "Chad");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CHL", "Chile");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CHN", "China");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("HKG", "China, Hong Kong Special Administrative Region");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MAC", "China, Macao Special Administrative Region");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("COL", "Colombia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("COM", "Comoros");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("COG", "Congo");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("COK", "Cook Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CRI", "Costa Rica");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CIV", "Côte d\'Ivoire");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("HRV", "Croatia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CUB", "Cuba");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CUW", "Curaçao");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CYP", "Cyprus");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CZE", "Czech Republic");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PRK", "Democratic People\'s Republic of Korea");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("COD", "Democratic Republic of the Congo");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("DNK", "Denmark");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("DJI", "Djibouti");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("DMA", "Dominica");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("DOM", "Dominican Republic");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ECU", "Ecuador");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("EGY", "Egypt");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SLV", "El Salvador");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GNQ", "Equatorial Guinea");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ERI", "Eritrea");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("EST", "Estonia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ETH", "Ethiopia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("FRO", "Faeroe Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("FLK", "Falkland Islands (Malvinas)");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("FJI", "Fiji");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("FIN", "Finland");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("FRA", "France");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GUF", "French Guiana");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PYF", "French Polynesia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GAB", "Gabon");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GMB", "Gambia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GEO", "Georgia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("DEU", "Germany");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GHA", "Ghana");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GIB", "Gibraltar");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GRC", "Greece");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GRL", "Greenland");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GRD", "Grenada");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GLP", "Guadeloupe");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GUM", "Guam");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GTM", "Guatemala");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GGY", "Guernsey");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GIN", "Guinea");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GNB", "Guinea-Bissau");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GUY", "Guyana");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("HTI", "Haiti");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("VAT", "Holy See");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("HND", "Honduras");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("HUN", "Hungary");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ISL", "Iceland");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("IND", "India");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("IDN", "Indonesia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("IRN", "Iran (Islamic Republic of)");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("IRQ", "Iraq");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("IRL", "Ireland");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("IMN", "Isle of Man");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ISR", "Israel");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ITA", "Italy");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("JAM", "Jamaica");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("JPN", "Japan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("JEY", "Jersey");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("JOR", "Jordan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("KAZ", "Kazakhstan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("KEN", "Kenya");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("KIR", "Kiribati");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("KWT", "Kuwait");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("KGZ", "Kyrgyzstan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LAO", "Lao People\'s Democratic Republic");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LVA", "Latvia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LBN", "Lebanon");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LSO", "Lesotho");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LBR", "Liberia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LBY", "Libya");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LIE", "Liechtenstein");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LTU", "Lithuania");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LUX", "Luxembourg");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MDG", "Madagascar");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MWI", "Malawi");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MYS", "Malaysia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MDV", "Maldives");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MLI", "Mali");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MLT", "Malta");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MHL", "Marshall Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MTQ", "Martinique");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MRT", "Mauritania");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MUS", "Mauritius");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MYT", "Mayotte");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MEX", "Mexico");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("FSM", "Micronesia (Federated States of)");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MCO", "Monaco");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MNG", "Mongolia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MNE", "Montenegro");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MSR", "Montserrat");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MAR", "Morocco");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MOZ", "Mozambique");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MMR", "Myanmar");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NAM", "Namibia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NRU", "Nauru");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NPL", "Nepal");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NLD", "Netherlands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NCL", "New Caledonia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NZL", "New Zealand");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NIC", "Nicaragua");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NER", "Niger");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NGA", "Nigeria");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NIU", "Niue");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NFK", "Norfolk Island");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MNP", "Northern Mariana Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("NOR", "Norway");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("OMN", "Oman");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PAK", "Pakistan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PLW", "Palau");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PAN", "Panama");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PNG", "Papua New Guinea");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PRY", "Paraguay");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PER", "Peru");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PHL", "Philippines");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PCN", "Pitcairn");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("POL", "Poland");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PRT", "Portugal");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PRI", "Puerto Rico");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("QAT", "Qatar");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("KOR", "Republic of Korea");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MDA", "Republic of Moldova");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("REU", "Réunion");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ROU", "Romania");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("RUS", "Russian Federation");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("RWA", "Rwanda");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("BLM", "Saint Barthélemy");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SHN", "Saint Helena");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("KNA", "Saint Kitts and Nevis");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LCA", "Saint Lucia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MAF", "Saint Martin (French part)");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SPM", "Saint Pierre and Miquelon");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("VCT", "Saint Vincent and the Grenadines");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("WSM", "Samoa");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SMR", "San Marino");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("STP", "Sao Tome and Principe");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SAU", "Saudi Arabia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SEN", "Senegal");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SRB", "Serbia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SYC", "Seychelles");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SLE", "Sierra Leone");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SGP", "Singapore");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SXM", "Sint Maarten (Dutch part)");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SVK", "Slovakia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SVN", "Slovenia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SLB", "Solomon Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SOM", "Somalia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ZAF", "South Africa");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SSD", "South Sudan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ESP", "Spain");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("LKA", "Sri Lanka");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("PSE", "State of Palestine");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SDN", "Sudan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SUR", "Suriname");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SJM", "Svalbard and Jan Mayen Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SWZ", "Swaziland");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SWE", "Sweden");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("CHE", "Switzerland");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("SYR", "Syrian Arab Republic");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TJK", "Tajikistan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("THA", "Thailand");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("MKD", "The former Yugoslav Republic of Macedonia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TLS", "Timor-Leste");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TGO", "Togo");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TKL", "Tokelau");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TON", "Tonga");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TTO", "Trinidad and Tobago");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TUN", "Tunisia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TUR", "Turkey");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TKM", "Turkmenistan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TCA", "Turks and Caicos Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TUV", "Tuvalu");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("UGA", "Uganda");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("UKR", "Ukraine");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ARE", "United Arab Emirates");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("GBR", "United Kingdom of Great Britain and Northern Ireland");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("TZA", "United Republic of Tanzania");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("USA", "United States of America");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("VIR", "United States Virgin Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("URY", "Uruguay");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("UZB", "Uzbekistan");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("VUT", "Vanuatu");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("VEN", "Venezuela (Bolivarian Republic of)");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("VNM", "Viet Nam");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("WLF", "Wallis and Futuna Islands");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ESH", "Western Sahara");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("YEM", "Yemen");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ZMB", "Zambia");
INSERT INTO {wp_projectmanager_countries} (code, name) VALUES ("ZWE", "Zimbabwe");
